spring.application.name=library-automation

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.app.jwtSecret=mySecretKey123912738asdasdasdadadadasdasdasdasdasdas
spring.app.jwtExpirationMs=300000000
spring.app.jwtCookieName=library-automation